// Code generated by protoc-gen-go.
// source: tweet.proto
// DO NOT EDIT!

/*
Package tweet is a generated protocol buffer package.

It is generated from these files:
	tweet.proto

It has these top-level messages:
	Tweet
*/
package tweet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Tweet struct {
	Tweet         string `protobuf:"bytes,1,opt,name=tweet" json:"tweet,omitempty"`
	IngestionDate string `protobuf:"bytes,2,opt,name=ingestion_date,json=ingestionDate" json:"ingestion_date,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	TweetId       string `protobuf:"bytes,4,opt,name=tweet_id,json=tweetId" json:"tweet_id,omitempty"`
}

func (m *Tweet) Reset()                    { *m = Tweet{} }
func (m *Tweet) String() string            { return proto.CompactTextString(m) }
func (*Tweet) ProtoMessage()               {}
func (*Tweet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Tweet) GetTweet() string {
	if m != nil {
		return m.Tweet
	}
	return ""
}

func (m *Tweet) GetIngestionDate() string {
	if m != nil {
		return m.IngestionDate
	}
	return ""
}

func (m *Tweet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tweet) GetTweetId() string {
	if m != nil {
		return m.TweetId
	}
	return ""
}

func init() {
	proto.RegisterType((*Tweet)(nil), "Tweet")
}

func init() { proto.RegisterFile("tweet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x29, 0x4f, 0x4d,
	0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x2a, 0xe6, 0x62, 0x0d, 0x01, 0x71, 0x85, 0x44,
	0xb8, 0x58, 0xc1, 0xe2, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x90, 0x2a, 0x17,
	0x5f, 0x66, 0x5e, 0x7a, 0x6a, 0x71, 0x49, 0x66, 0x7e, 0x5e, 0x7c, 0x4a, 0x62, 0x49, 0xaa, 0x04,
	0x13, 0x58, 0x9a, 0x17, 0x2e, 0xea, 0x92, 0x58, 0x92, 0x2a, 0x24, 0xc4, 0xc5, 0x92, 0x97, 0x98,
	0x9b, 0x2a, 0xc1, 0x0c, 0x96, 0x04, 0xb3, 0x85, 0x24, 0xb9, 0x38, 0xc0, 0x66, 0xc4, 0x67, 0xa6,
	0x48, 0xb0, 0x80, 0xc5, 0xd9, 0xc1, 0x7c, 0xcf, 0x94, 0x24, 0x36, 0xb0, 0xdd, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xfb, 0x17, 0xb8, 0xd2, 0x8a, 0x00, 0x00, 0x00,
}
